services:
  amo_server:
    build: ./server/
    container_name: amo_server
    volumes:
      - ./Data:/Data
    networks:
      - bot-network
    ports:
      - "80:80"
    env_file:
      - .env  

  telegram_bot:
    build: ./TG_bot/
    container_name: telegram_bot
    volumes:
      - ./Data:/Data
    networks:
      - bot-network
    depends_on: 
      - amo_server
    env_file:
      - .env 

networks:
  bot-network:
    driver: bridge